model: convnext_base
pretrained: true
num_classes: 10
img_size: 224
batch_size: 64

# hflip: 0
# vflip: 0
# scale: [0.9, 1.0]  
# ratio: [1.0,1.0]
# color_jitter: 0

opt: momentum
lr: 1e-2 #1e-2
weight-decay: 1e-4

epochs: 120
sched: step
decay_epochs: 40
decay_rate: 0.1


cutmix: 1.0
reprob: 0.5

aa: corr-aug
# aa: rand-m9-mstd0.5-inc1

#mixup-prob: 0.5
